### ISSUE TITLE
Fine-tuning Script for LVOS

### ISSUE THREAD

**Issue by Amshaker** [LingyiHongfd/LVOS#4]
Hi,

You mentioned in the paper that the results of DDMemory are improved after fine-tuning on LVOS. 

Before fine-tuning, my method is on par with yours. Could you please share the fine-tuning script to do that and compare the performance after fine-tuning under the same fine-tuning recipe? This will be much appreciated since we have a paper submission after one week.

Best regards,
Abdelrahman.

**Comment by Amshaker** [comment]
@LingyiHongfd Your fast reply is highly appreciated.

**Comment by LingyiHongfd** [comment]
Sorry for late response as we are occupied with some chores. We are preparing the LVOS v2 with more annotated videos and more  evaluation settings. All the codes will be released after we complete this project. Please stay tuned. Thank you again for your understanding and support of our work!

**Comment by LingyiHongfd** [comment]
Hi, we have released LVOS V2! Please see the homepage of LVOS for more details. Dataset is available, and code will be released within a few days. We hope that our LVOS V2 can help your research.

Best regards,
Lingyi

**Comment by LingyiHongfd** [comment]
I will close it for now. Feel free to open it in case of future questions!
