### ISSUE TITLE
LVOS attributes

### ISSUE THREAD

**Issue by Vujas-Eteph** [LingyiHongfd/LVOS#5]
Hi there 👋 !

Thank you for providing the dataset! It's a great alternative to the vanilla/chocolate flavored ones (DAVIS/Y-VOS 👀).

I currently use your dataset for my evaluations and would like to visualize my failure cases depending on some attributes (*e.g.*, occlusion, size variation, *etc*).
You have those attributes listed in the paper, but I couldn't find them in the annotations files.
![image](https://github.com/LingyiHongfd/LVOS/assets/106599787/b2c744ea-90c3-4d7d-9fba-9756fa9b769b)

Could you help me with this? Is there a file in the dataset that summarizes which attributes occur in a particular sequence for instance?

Cheers!

**Comment by LingyiHongfd** [comment]
Hi, thanks for your interest! We didn't release the video attributes. We will release a new vision of LVOS with more videos in the soon future, and we will add the attributes into the annotation files. Please stay tuned!

**Comment by Vujas-Eteph** [comment]
That’s awesome! :fire: Please keep me updated via the issue!
Although, may I know about the timeline (*i.e.*, in one month or two?)? To better plan my experiments 😊

Cheers

**Comment by LingyiHongfd** [comment]
That's fine. About the timeline, we will publish the new version in March if nothing else. We will release them as soon as possible.

**Comment by LingyiHongfd** [comment]
Hi, sry for the late reply due a series of reasons. We have released LVOS V2. You can refer to the [homepage](https://lingyihongfd.github.io/lvos.github.io/) for more information. I hope that LVOS V2 can help your research.

**Comment by Vujas-Eteph** [comment]
Hi, thanks for the update! I'll make sure to include the new dataset in my research ;)

**Comment by Vujas-Eteph** [comment]
Hi again !

Great work on LVOS 2! While reviewing the attributes, I noticed a discrepancy between the terminology used in the paper and the .json files. In the paper, you refer to "CTC" (Cross-temporal Confusion), but in the .json files, the corresponding attribute is labeled as "MSO."

Could you please clarify whether "MSO" is equivalent to "CTC"? If not, could you explain what "MSO" stands for and how it relates to the attributes discussed in the paper?

Thanks in advance 😃

**Comment by LingyiHongfd** [comment]
Hi. It is our oversight to cause this error. We have fixed the attribute file so that the content in the .json file is consistent with that in the paper. We have updated the corresponding files both in Google Drive and Baidu Pan.

If you have any question, please feel free to contact me.

Bests,
Lingyi

**Comment by Vujas-Eteph** [comment]
Great! Many thanks for the clarification and for the quick update!👍

([Link to attributes](https://lingyihongfd.github.io/lvos.github.io/dataset.html) for future references)

Cheers,
Stéphane
