### ISSUE TITLE
training code for LVOS

### ISSUE THREAD

**Issue by Z0721Z** [LingyiHongfd/LVOS#7]
Dear Author,

I am currently working on a CT space sequence segmentation project. Specifically, I am interested in your training code. If you could provide me with the training code or any other information/documentation to help me understand and utilize your work, I would greatly appreciate it.

Best regards,

Kaly

**Comment by LingyiHongfd** [comment]
Dear Katy:

Thanks for your interest on our works. If I've understood you correctly, you're inquiring about the code used to train your own model with the LVOS dataset, right?  Indeed, we utilize the training code specific to a given model. For instance, when training AOT, we only adjust the dataset-related code for AOT. I think that it is easy to modify your code to make it support the training of LVOS within a few minutes. 

If you have any other questions, feel free to contact me.

Best regards,
Lingyi

**Comment by LingyiHongfd** [comment]
I will close this issue. If you have any question, please feel free to reopen it.
